### ISSUE TITLE
weblogolib renamed to weblogo in 3.7

### ISSUE THREAD

**Issue by vineetbansal** [betteridiot/seqlogo#3]
Hello,
I'm trying to use seqlogo using the latest version of weblogo (3.7.1), and among other changes, it seems that `weblogolib` has been renamed to `weblogo`. So perhaps a very high level import check is desirable in seqlogo.py:

```
try:
  import weblogolib as wl
except ImportError:
  import weblogo as wl
```

I understand that seqlogo explicitly lists weblogo 3.6.0 as the requirement, but in my case, I cannot use 3.6.0 because of other bugs that weblogo has fixed in the meantime, so any help here would be appreciated.

Once I do make this change, I'm able to use the package correctly to generate logo png files, indicating that perhaps not a lot of changes are needed downstream.

Thanks!

**Comment by nekrut** [comment]
This is definitely a problem and replacing `import weblogolib as wl` to `import weblogo as wl` does solve it

**Comment by betteridiot** [comment]
Thank you for bringing this to my attention. Unfortunately, I just got out of the hospital and have very little bandwidth. If you feel up to making a PR for this that will support both versions of `weblogo` I would be more than happy to merge it.
