### ISSUE TITLE
seqlogo can't render two PWMs in jupyter notebook

### ISSUE THREAD

**Issue by alexlenail** [betteridiot/seqlogo#5]
**Describe the bug**
It isn't possible to properly render two seqlogos in the same jupyter notebook, as far as I can tell. There's some sort of leaky state  in the seqlogo package. 

**To Reproduce**
1. Open a jupyter notebook
2. `import seqlogo`
3. get two PWMs as numpy arrays
4. `seqlogo.seqlogo(seqlogo.Ppm(your_first_pwm)); seqlogo.seqlogo(seqlogo.Ppm(your_second_pwm))`

The error occurs whether you try to render both PWMs from the same cell or different cells in the same notebook. 

**Expected behavior**
Should properly render both PWMs

**Screenshots**
![Screen Shot 2019-08-09 at 7 33 01 PM](https://user-images.githubusercontent.com/2761597/62814094-9496e800-badc-11e9-9637-35c0f2cf3cf4.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Python Version 3.7.3
 - NumPy Version 1.16.4
 - Pandas Version 0.24.2
 - matplotlib Version 3.1.0

**Comment by betteridiot** [comment]
What happens if you try to render them in two different cells?

**Comment by alexlenail** [comment]
@betteridiot that fails as well. I discovered that first. Interestingly, if you render in two different cells, and delete either cell, without even re-running the first cell, the plot is corrected. 

Can you reproduce this?

**Comment by betteridiot** [comment]
I will have to look into this. I am guessing it is how seqlogo integrates with `IPython.display.SVG`

This may take me a couple of days to get to though. In the meantime, if it isn't too much of an inconvenience, you can save the SVGs (without displaying them).

**Comment by betteridiot** [comment]
After a quick look into this (https://github.com/betteridiot/seqlogo/blob/b8d6fbb4df33a40a7bcf63cc4fd3312af652a622/seqlogo/seqlogo.py#L95-L105), the `out` variable that captures the SVG data is never de-referenced explicitly. This may result in these errors.

**Comment by betteridiot** [comment]
I cannot seem to reproduce your results. 
As I do not know anything about your `motifs` object and how it defines `pwm`, I make the assumption that your `motifs.pwm` is actually a PPM since you have `seqlogo.Ppm` ingest the data. 

I should also mention that I am using [jupyterlab](https://github.com/jupyterlab/jupyterlab) for my testing and development.

From that assumption, here has been my workflow (screenshot below):
```python
import numpy as np
import pandas as pd
import seqlogo as sl

np.random.seed(42)
first_random_ppm = sl.Ppm(np.random.dirichlet(np.ones(4), size=6))
sl.seqlogo(first_random_ppm, format='svg', size='medium')

np.random.seed(420)
second_random_ppm = sl.Ppm(np.random.dirichlet(np.ones(4), size=6))
sl.seqlogo(second_random_ppm, format='svg', size='medium')
```
![image](https://user-images.githubusercontent.com/25447319/62962725-79262880-bdcd-11e9-9ad3-fc27d6e69e98.png)


**Note**: If you continue having issues with `seqlogo` (knowing that is was primarily designed as an educational tool for early bioinformaticists), you should look at @jbkinney's [logomaker](https://logomaker.readthedocs.io/) for more scalable/production-oriented solutions

**Comment by alexlenail** [comment]
Jupyter: 

<img width="462" alt="Screen Shot 2019-08-14 at 11 11 02 AM" src="https://user-images.githubusercontent.com/2761597/63032676-468b3700-be84-11e9-87b3-ec9a88af9c99.png">

Jupyter Lab: 

<img width="536" alt="Screen Shot 2019-08-14 at 11 12 51 AM" src="https://user-images.githubusercontent.com/2761597/63032802-86521e80-be84-11e9-9bdb-a8d9783b6e9a.png">

Could you try reproducing the bug in vanilla jupyter?

**Comment by betteridiot** [comment]
I am able to reproduce this in vanilla notebook, but I have no idea why this is doing what is doing. I am looking into it though. 

The main curiosity is that it works fine in lab and not vanilla notebook. This must mean that two have different ways of interacting with `IPython.display.SVG`.

**Comment by betteridiot** [comment]
After some _fun_ debugging, I found out that the issue isn't with `seqlogo`...it is with the _notebook_ itself. You can find out the full details at https://github.com/ipython/ipython/issues/1866/, but the TLDR is that vanilla notebooks rendered SVGs like they were images. However, they really aren't. The things that make up SVGs are called glyphs. Each glyph has a unique id.

This is all fine, but when a notebook generates the SVG, it doesn't properly handle glyph id collisions, such that two different SVGs may have a `glyph0-1`. As theses glyphs get painted on the DOM (document object model), the glyph collisions occur, causing what you saw above.

I fixed this by parsing the raw SVG data, and inserting the hash value of the original data onto each occurrence of a glyph id--making them unique. Below are the steps I used to make sure this works on vanilla notebook (screenshot below):

```python
import numpy as np
import pandas as pd
import seqlogo as sl

np.random.seed(42)
first_random_ppm = sl.Ppm(np.random.dirichlet(np.ones(4), size=6))

sl.seqlogo(first_random_ppm, format='svg', size='medium')
# first_random_ppm SVG here

np.random.seed(420)
second_random_ppm = sl.Ppm(np.random.dirichlet(np.ones(4), size=6))

sl.seqlogo(second_random_ppm, format='svg', size='medium')
# second_random_ppm SVG here
```
![image](https://user-images.githubusercontent.com/25447319/63049238-37b57c00-bea6-11e9-9261-d16c50a316ae.png)

**Comment by alexlenail** [comment]
Thank you!

**Comment by betteridiot** [comment]
This may take a moment to be conda installable, but you can always pip install it as well

**Comment by betteridiot** [comment]
Also, if you feel like this was helpful, please feel free to star this rep and maybe drop a tweet about this experience (twitter handle: @better_idiot). 

Thanks for bringing this up.
