### ISSUE TITLE
Matrix conversion and creation does not work when using amino acid sequences

### ISSUE THREAD

**Issue by weitzner** [betteridiot/seqlogo#6]
**Description of the bug**
The library doesn't work with amino acid sequences. There are lots of internal parts that seem to omit the supplied `alphabet_type` parameter, which causes it to default to `DNA`. Then it throws an error because there are more than 4 letters.

**To Reproduce**
```python
pfm = np.zeros((len(list_of_seqs), 20))
for seq in list_of_seqs:
    for i, aa in enumerate(seq):
        pfm[i, aa_alphabet.index(aa)] += 1
pfm = seqlogo.Pfm(pfm, alphabet_type="AA")
ppm = seqlogo.Ppm(seqlogo.pfm2ppm(pfm, alphabet_type="AA"), alphabet_type="AA")
```
This raises 
```python
ValueError: None alphabet selected, but PM is not 4 rows long
```

**Expected behavior**
This should create a `Ppm` instance.

**Additional context**
I found a _slight_ workaround by creating a `Pfm` instead. This then fails when attempting to produce the weblogo itself:
```python
pfm = np.zeros((len(list_of_seqs), 20))
for seq in list_of_seqs:
    for i, aa in enumerate(seq):
        pfm[i, aa_alphabet.index(aa)] += 1
pfm = seqlogo.Pfm(pfm, alphabet_type="AA")
ppm = seqlogo.Pfm(seqlogo.pfm2ppm(pfm, alphabet_type="AA"), alphabet_type = "AA")

seqlogo.seqlogo(ppm, ic_scale = False, size = 'medium')
```
However, this raises
```python
TypeError: must be str, not bytes
```
which is surprising because this is a python 3.x only library.

**Comment by betteridiot** [comment]
I see your issue and thank you for bringing it to my attention. I will have to do a little "play testing" on my end to get reacquainted with the code base. 

In an attempt to not minimize the issue you posted, if your work is a bit time sensitive and in need of a quick fix, please  also consider  @jbkinney's [logomaker](https://logomaker.readthedocs.io/en/latest/) as its plotting capabilities are bit more robust and fleshed out compared to mine--with no dependency on weblogo as well.

Hopefully, though, I can resolve your issue quickly. Sorry for the inconvenience.

**Comment by betteridiot** [comment]
Sorry for the long delay in responding. Campus life got a little real and I finally have some bandwidth for this. 

The problem doesn't actually arise in the creating of the `seqlogo.Pfm`:
```python
import random
import numpy as np
import pandas as pd

import seqlogo


def gen_seqs(n, length=25, alphabet_type='AA', seed = None):
    """Pseudo-random generation of simulated sequences
    
    Args:
        n (int): The desired number of sequences
        length (int): The length (bp/aa) of the desired sequences (default: 25)
        alphabet_type (str): Desired alphabet to sample from (default: 'AA')
            Choose from:
                "DNA" := "ACGT"
                "reduced DNA" := "ACGTN-"
                "ambig DNA" := "ACGTRYSWKMBDHVN-"
                "RNA" := "ACGU"
                "reduced RNA" := "ACGUN-"
                "ambig RNA" := "ACGURYSWKMBDHVN-"
                "AA" : = "ACDEFGHIKLMNPQRSTVWY"
                "reduced AA" := "ACDEFGHIKLMNPQRSTVWYX*-"
                "ambig AA" := "ACDEFGHIKLMNOPQRSTUVWYBJZX*-"
        seed (int): random seed for testing (default: None)
    
    Returns:
        (list): n length list of length long sequences 
    """
    random.seed(seed)
    return [''.join(random.choices(seqlogo.utils._IDX_LETTERS[alphabet_type], k=length)) for _ in range(n)]


# Make my simulated sequences
alphabet_type = 'AA'
list_of_seqs = gen_seqs(15, alphabet_type = alphabet_type)

# For duplicating aa_alphabet using supported alphabets
aa_alphabet = seqlogo.utils._IDX_LETTERS[alphabet_type]

# Make the sample PFM (MODIFIED FROM ISSUE)
pfm = np.zeros((len(list_of_seqs), 20))
for i, seq in enumerate(list_of_seqs): 
    for aa in seq:
        pfm[i, aa_alphabet.index(aa)] += 1

# Convert into a seqlogo.Pfm
pfm = seqlogo.Pfm(pfm, alphabet_type="AA")

# Get some summary data
print(f"""{pfm}
Pfm alphabet_type:  {pfm.alphabet_type}
Pfm alphabet:       {pfm.alphabet}
Number of Rows:     {pfm.shape[0]}
Number of Columns : {pfm.shape[1]}
""")
```
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>A</th>
      <th>C</th>
      <th>D</th>
      <th>E</th>
      <th>F</th>
      <th>G</th>
      <th>H</th>
      <th>I</th>
      <th>K</th>
      <th>L</th>
      <th>M</th>
      <th>N</th>
      <th>P</th>
      <th>Q</th>
      <th>R</th>
      <th>S</th>
      <th>T</th>
      <th>V</th>
      <th>W</th>
      <th>Y</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>5.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>3.0</td>
      <td>3.0</td>
      <td>3.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2.0</td>
      <td>2.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>5.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>0.0</td>
      <td>3.0</td>
      <td>1.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>2.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>3.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2.0</td>
      <td>0.0</td>
      <td>4.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>3.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>2.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>3.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>3.0</td>
      <td>4.0</td>
      <td>0.0</td>
      <td>2.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>3.0</td>
      <td>0.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>5</th>
      <td>2.0</td>
      <td>3.0</td>
      <td>1.0</td>
      <td>3.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>2.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>6</th>
      <td>0.0</td>
      <td>3.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>3.0</td>
      <td>3.0</td>
      <td>3.0</td>
      <td>4.0</td>
      <td>3.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>7</th>
      <td>2.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>3.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>3.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>4.0</td>
    </tr>
    <tr>
      <th>8</th>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>2.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>3.0</td>
      <td>2.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>9</th>
      <td>1.0</td>
      <td>2.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>3.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>4.0</td>
    </tr>
    <tr>
      <th>10</th>
      <td>0.0</td>
      <td>3.0</td>
      <td>2.0</td>
      <td>0.0</td>
      <td>5.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>2.0</td>
      <td>2.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>2.0</td>
      <td>2.0</td>
    </tr>
    <tr>
      <th>11</th>
      <td>3.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>3.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>3.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>2.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>3.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>12</th>
      <td>2.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>4.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>2.0</td>
      <td>3.0</td>
      <td>3.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>13</th>
      <td>0.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>3.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>6.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>2.0</td>
      <td>0.0</td>
      <td>2.0</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>14</th>
      <td>2.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>4.0</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>4.0</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>1.0</td>
    </tr>
  </tbody>
</table>

```bash
Pfm alphabet_type:  AA
Pfm alphabet:       ACDEFGHIKLMNPQRSTVWY
Number of Rows:     15
Number of Columns : 20
```

Converting the PFM to a PPM doesn't seem to be the issue either:

```python
seqlogo.pfm2ppm(pfm, alphabet_type='AA')
```

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>A</th>
      <th>C</th>
      <th>D</th>
      <th>E</th>
      <th>F</th>
      <th>G</th>
      <th>H</th>
      <th>I</th>
      <th>K</th>
      <th>L</th>
      <th>M</th>
      <th>N</th>
      <th>P</th>
      <th>Q</th>
      <th>R</th>
      <th>S</th>
      <th>T</th>
      <th>V</th>
      <th>W</th>
      <th>Y</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.08</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.12</td>
      <td>0.16</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.00</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.08</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.08</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0.20</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.08</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.08</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.08</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.00</td>
    </tr>
    <tr>
      <th>6</th>
      <td>0.16</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.00</td>
    </tr>
    <tr>
      <th>7</th>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.20</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.12</td>
    </tr>
    <tr>
      <th>8</th>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.20</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.12</td>
    </tr>
    <tr>
      <th>9</th>
      <td>0.12</td>
      <td>0.08</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.16</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.00</td>
    </tr>
    <tr>
      <th>10</th>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.12</td>
      <td>0.16</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
    </tr>
    <tr>
      <th>11</th>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.12</td>
      <td>0.08</td>
      <td>0.04</td>
    </tr>
    <tr>
      <th>12</th>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.20</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.12</td>
      <td>0.00</td>
      <td>0.04</td>
    </tr>
    <tr>
      <th>13</th>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.24</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.16</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.08</td>
      <td>0.04</td>
    </tr>
    <tr>
      <th>14</th>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.12</td>
      <td>0.12</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.04</td>
    </tr>
  </tbody>
</table>


---
# The Problem
The issue arises when we `seqlogo` uses the `pfm2ppm` function...which you highlighted on. This is in part due to some inheritance issues. In my development build, that is fixed.

The second issue (one that you brought up) is that certain arguments from the conversion functions (e.g. `pfm2ppm`) don't carry over to calls to `Ppm`. 

I have fixed this as well, and should have an update soon.

**Comment by betteridiot** [comment]
With these changes, the following works:

```python
ppm = seqlogo.Ppm(seqlogo.pfm2ppm(pfm, alphabet_type='AA'), alphabet_type = 'AA')
ppm
```

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>A</th>
      <th>C</th>
      <th>D</th>
      <th>E</th>
      <th>F</th>
      <th>G</th>
      <th>H</th>
      <th>I</th>
      <th>K</th>
      <th>L</th>
      <th>M</th>
      <th>N</th>
      <th>P</th>
      <th>Q</th>
      <th>R</th>
      <th>S</th>
      <th>T</th>
      <th>V</th>
      <th>W</th>
      <th>Y</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0.04</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.16</td>
      <td>0.12</td>
      <td>0.00</td>
      <td>0.04</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.12</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.04</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.12</td>
      <td>0.20</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.00</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.12</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.08</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.00</td>
      <td>0.16</td>
      <td>0.08</td>
      <td>0.08</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.20</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.04</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.16</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.08</td>
    </tr>
    <tr>
      <th>6</th>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.16</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.00</td>
    </tr>
    <tr>
      <th>7</th>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.16</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.04</td>
    </tr>
    <tr>
      <th>8</th>
      <td>0.12</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.16</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.04</td>
    </tr>
    <tr>
      <th>9</th>
      <td>0.04</td>
      <td>0.12</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.12</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.00</td>
    </tr>
    <tr>
      <th>10</th>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.20</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.00</td>
    </tr>
    <tr>
      <th>11</th>
      <td>0.08</td>
      <td>0.12</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.00</td>
    </tr>
    <tr>
      <th>12</th>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.16</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.24</td>
      <td>0.16</td>
    </tr>
    <tr>
      <th>13</th>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.12</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.12</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.08</td>
      <td>0.04</td>
    </tr>
    <tr>
      <th>14</th>
      <td>0.12</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.08</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.04</td>
      <td>0.00</td>
      <td>0.12</td>
      <td>0.08</td>
      <td>0.00</td>
      <td>0.00</td>
      <td>0.08</td>
      <td>0.04</td>
    </tr>
  </tbody>
</table>

**Comment by betteridiot** [comment]
I should have the updated version on PyPI soon, and bioconda should follow

**Comment by eloilit** [comment]
I'm currently experiencing a similar problem with the alphabet "ambig DNA". When creating an ambig DNA Pfm, it looks like it's immediately converted into a DNA Pfm, while my goal is to display an ambiguous DNA sequence.

When writing 
`A = seqlogo.Pfm(np.random.randint(0,36,size=(8,16)),alphabet_type="ambig DNA")`

an object with alphabet_type "DNA" is returned

**Comment by betteridiot** [comment]
While I am looking into this @eloilit, can you actually create a new issue for this please?
